### ISSUE TITLE
internal/tsdb: make decoderMaxSeries configurable?

### ISSUE THREAD

**Issue by pharaujo** [betfair/opentsp#10]
Our aggregator is constantly hitting the `too many time series` limit.

```
$ sudo tail -30000 /var/log/tsp/aggregator.log | uniq -c
    466 2014/12/17 17:13:34 collect.d/site.sh: too many time series (>1000000)
   3757 2014/12/17 17:13:37 collect.d/site.sh: too many time series (>1000000)
   2028 2014/12/17 17:13:39 collect.d/site.sh: too many time series (>1000000)
  11029 2014/12/17 17:13:52 collect.d/site.sh: too many time series (>1000000)
   1372 2014/12/17 17:13:53 collect.d/site.sh: too many time series (>1000000)
    863 2014/12/17 17:13:59 collect.d/site.sh: too many time series (>1000000)
      2 2014/12/17 17:14:00 collect.d/site.sh: too many time series (>1000000)
   1491 2014/12/17 17:14:04 collect.d/site.sh: too many time series (>1000000)
   6059 2014/12/17 17:14:05 collect.d/site.sh: too many time series (>1000000)
   2932 2014/12/17 17:14:07 collect.d/site.sh: too many time series (>1000000)
      1 2014/12/17 17:14:08 collect.d/site.sh: too many time series (>1000000)
```

Is there a reason why it's hardcoded to 1M? Can we make it configurable?

**Comment by andredasilvapinto** [comment]
+1

**Comment by masiulaniec** [comment]
The decoderMaxSeries limit is part of input validation of tsdb.Decoder. It's there because of the risk of erratic collection plugin that produces unbounded number of time series names.  Each new name comes at a memory cost.  Without the limit, the program using the library would be pushed to exhaust all available memory.  This would be bad for the program using the library (forwarder, poller, aggregator), and for neighbouring programs on the same machine.  With the limit, the memory growth is bounded, and as a bonus the operator sees an informative error message that is more helpful than just seeing swapping in vmstat.

So decoderMaxSeries is an upper bound that 'should be enough for everyone'.

I want to fix this issue in a way that does not burden the operator with the task of maintaining a configuration setting. I came up with the following heuristic:

tsp-aggregator: bump the limit to 2,000,000
tsp-poller: drop to 200,000
tsp-forwarder: drop to 20,000

I'm not wedded to the specific numbers. The key idea is to have a safe cutoff point that is appropriate in the given context. For example, it feels right for tsp-forwarder to be defensive and never allocate 2G+ RSS on behalf of an erratic collection plugin.

**Comment by masiulaniec** [comment]
Also, I would give 'tcpdump -A dst port 4242' a look. It might be the case that some collector is contributing more metrics than is sensible. Maybe some metric needs dimensionality reduction using the /etc/tsp-controller/filter mechanism? I recall Betfair's time series namespace was well under the 1M limit not so long ago...

**Comment by J-Brooks** [comment]
I ran `tcpdump -s 0 -A 'dst port 4242' 2>&1 | grep put | sed -e s/.*put/put/ > time_series` for 10 seconds to try and capture a good sample of the incoming time series

    wc -l time_series 
    923308 time_series

```
awk {'print $2'} time_series | sort | uniq -c | sort -n | tail -20
   3682 os.events
   3745 os.file.Descriptor
   5024 os.ip.counter
   6085 os.nic.packets
   6126 os.nic.bytes
  10047 os.cpu.seconds
  10156 os.socket.counter
  12061 os.nic.errors
  14204 java.memory.pool.Usage
  14514 java.memory.pool.PeakUsage
  17253 os.filesystem.size-inodes
  17414 os.filesystem.size
  19506 os.filesystem.bytes
  19654 os.filesystem.ops
  19660 os.filesystem.seconds
  29309 os.log.size
  33256 os.spool.size
  43218 os.memory.counter
  43332 os.tcp.counter
  49145 os.filesystem.counter
```

None of the metric names immediately leap out as being a problem

**Comment by masiulaniec** [comment]
Could you also verify that tcpdump managed to observe each time series at least once? The time_series file is expected to hold over 1 million unique time series. The snippet above counts only 0.37 million, which feels too low: it's not even the majority of the namespace.

**Comment by masiulaniec** [comment]
IOW, there is a long tail that consumes the majority of the namespace. I would also try analysing the data by viewing series count grouped by cluster (based the cluster tag), and maybe normalise it by dividing by host count (or by removing the host dimension and piping to |sort|uniq -c).

**Comment by masiulaniec** [comment]
I am now thinking that maybe aggregator should be exempted from making this check. If all data point submissions arrive from tsp-forwarder and tsp-poller, then we could simply depend on them making these checks. In this case I would *reduce* decoderMaxSeries from 1 million to 100K (it's a per-plugin limit).
